language: objective-c
script:
  - xctool -workspace iOSTravisSpike.xcworkspace -scheme iOSTravisSpike -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace iOSTravisSpike.xcworkspace -scheme iOSTravisSpikeTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO